"""Build and edit single-file ``.tscpkg`` plots.

:mod:`PlotManager.model` is dependency-free; :mod:`PlotManager.Main` adds the
optional PySide6 asset manager window.
"""

from .model import (
    MusicDraft,
    MusicEntry,
    PackError,
    PackageInfo,
    ScriptEntry,
    add_music,
    add_script,
    add_tracks,
    bind_music,
    character_table,
    create_package,
    inspect,
    music_config,
    pack_directory,
    read_script,
    remove_music,
    remove_script,
    replace_script,
    save_copy,
    script_member_name,
    script_text,
    suggest_abbreviation,
    track,
    update_characters,
    update_metadata,
    update_track,
    write_script,
)

__all__ = [
    "MusicDraft",
    "MusicEntry",
    "PackError",
    "PackageInfo",
    "ScriptEntry",
    "add_music",
    "add_script",
    "add_tracks",
    "bind_music",
    "character_table",
    "create_package",
    "inspect",
    "music_config",
    "pack_directory",
    "read_script",
    "remove_music",
    "remove_script",
    "replace_script",
    "save_copy",
    "script_member_name",
    "script_text",
    "suggest_abbreviation",
    "track",
    "update_characters",
    "update_metadata",
    "update_track",
    "write_script",
]
