"""One window for the whole authoring flow.

:mod:`Studio.model` is dependency-free and covers characters, scripts, timings
and music; :mod:`Studio.Main` adds the PySide6 wizard that drives it.
"""

from .model import (
    CHARACTERS_SUFFIX,
    CLEAR,
    DIALOGUE,
    EVENT_LABELS,
    HISTORY_DIR,
    MUSIC,
    NARRATION,
    PROJECT_SUFFIX,
    SLEEP,
    StudioError,
    StudioProject,
    characters_document,
    characters_text,
    collect_source,
    describe_event,
    dialogue_count,
    event_kind,
    event_label,
    export_playable,
    is_importable,
    is_project,
    is_script_timed,
    missing_characters,
    next_script_name,
    normalise_script,
    parse_character_json,
    parse_character_text,
    parse_characters,
    parse_script_text,
    safe_script_name,
    script_characters,
    timed_slots,
    timing_progress,
    write_characters,
)

__all__ = [
    "CHARACTERS_SUFFIX",
    "CLEAR",
    "DIALOGUE",
    "EVENT_LABELS",
    "HISTORY_DIR",
    "MUSIC",
    "NARRATION",
    "PROJECT_SUFFIX",
    "SLEEP",
    "StudioError",
    "StudioProject",
    "characters_document",
    "characters_text",
    "collect_source",
    "describe_event",
    "dialogue_count",
    "event_kind",
    "event_label",
    "export_playable",
    "is_importable",
    "is_project",
    "is_script_timed",
    "missing_characters",
    "next_script_name",
    "normalise_script",
    "parse_character_json",
    "parse_character_text",
    "parse_characters",
    "parse_script_text",
    "safe_script_name",
    "script_characters",
    "timed_slots",
    "timing_progress",
    "write_characters",
]
